name: Nightly release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  nightly-release:
    name: "Nightly release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: |
          mvn clean package
          zip -r stdlib.zip stdlib/
          tar -czvf stdlib.tar.gz stdlib/
      - uses: "marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1"  # Use commit sha to prevent supply chain attacks
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly release"
          files: |
            LICENSE
            edinaj/target/edinaj.jar
            eddoc/target/eddoc.jar
            cli/target/edina-cli.jar
            stdlib.zip
            stdlib.tar.gz